//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFetcherDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_UrlContent
    {
        public System.Guid Id { get; set; }
        public string HtmlUrl { get; set; }
        public string WebhookUrl { get; set; }
        public string ResultHtml { get; set; }
        public string UrlContentStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
